loggging med mdc
navikt/tms-common-lib pull request #3
Opened 2023-10-24 12:51 UTC by rannveigskjerve

2023-10-25 08:08 UTC, chris-santa commented on metrics/src/main/kotlin/observability/Tracelogging.kt
> +    disable, enable, updated, deleted, created, oppgave, innboks, beskjed
Tror event blir litt awkward. Disse ser ut som de er kafka-spesifike, og det bør eies av appene selv. Kanskje noe som "Tema" eller "Område" som kan være MF, varsel eller utkast (evt dokument og utbetaling også)?

2023-10-25 08:08 UTC, chris-santa requested changes
Kommentar

2023-10-26 07:57 UTC, rannveigskjerve commented on metrics/src/main/kotlin/observability/Tracelogging.kt
> +    disable, enable, updated, deleted, created, oppgave, innboks, beskjed
Godt poeng!

2023-10-26 09:07 UTC, chris-santa approved these changes

2023-10-26 09:09 UTC, merged